### ISSUE TITLE
Use metric units instead of pixels

### ISSUE THREAD

**Issue by sidorares** [AirWM/AirWM#15]
Just a suggestion: I currently have 227 ppi and 109 ppi displays side by side.  X connection gives you physical dimensions (in millimeters) + you can query more info via randr. Would it be a better idea to use "2mm" for example as margin value instead of "10 px" ?

**Comment by harmjan** [comment]
We currently use hard-coded metric values, we still need to make it configurable but this issue is fixed.

**Comment by sidorares** [comment]
:+1:
