### ISSUE TITLE
Grab keys when focussed on a window

### ISSUE THREAD

**Issue by nspruit** [AirWM/AirWM#38]
Now, the key bindings are only recognized (and its actions are only executed) when you first click in the margin between windows. When focussed on for instance xterm, the key presses are not recognized (command does not appear in the log).

**Comment by MartinRogalla** [comment]
I suggest we make this a high priority issue, since this really limits the working of the window manager right now.

**Comment by MartinRogalla** [comment]
After trying to debug this for a while with node-inspector I believe I might have found something. When numlock is enabled for me, this doesn't work, which would mean that there is probably a problem with ignoring 'irrelevant' key-modifiers. Will look and see if I can find where that goes wrong. If I disable numlock, everything works fine.

**Comment by MartinRogalla** [comment]
Yes, this is exactly where it goes wrong, we should also grab the key with other 'irrelevant' modifiers active.
https://github.com/AirWM/AirWM/blob/bfcd26bc106f32cf26716b8f7851d67ac96698ef/lib/airwm.js#L69
