### ISSUE TITLE
Fix phantom windows bug

### ISSUE THREAD

**Issue by nspruit** [AirWM/AirWM#8]

**Comment by nspruit** [comment]
@harmjan @MartinRogalla Does this bug still exist? Otherwise this issue can be closed

**Comment by nspruit** [comment]
Again, @harmjan @MartinRogalla does this bug still exist?

**Comment by harmjan** [comment]
I don't know, I think this can be closed and if this happens again re-opened.

**Comment by MartinRogalla** [comment]
Bug is resolved.
